/* hospitals_data.js — MedbookWB Hospital Registry */

const hospitalsDB = [
  {"id":"MBH01001","name":"Apollo Hospital","district":"Kolkata","location":"Salt Lake","password":"Apollo@123"},
  {"id":"MBH01002","name":"Peerless Clinic","district":"Kolkata","location":"New Alipore","password":"NH70D7F2"},
  {"id":"MBH01003","name":"AMRI Super Speciality","district":"Kolkata","location":"Garia","password":"NH7BC6DB"},
  {"id":"MBH01004","name":"Ruby Health Institute","district":"Kolkata","location":"Behala","password":"NHA64C39"},
  {"id":"MBH01005","name":"Belle Vue Medical Centre","district":"Kolkata","location":"Tollygunge","password":"NHEC7A41"},
  {"id":"MBH01006","name":"Woodlands Multispeciality Hospital","district":"Kolkata","location":"Kasba","password":"NH55284F"},
  {"id":"MBH01007","name":"Desun Medicare","district":"Kolkata","location":"Jadavpur","password":"NH63CC6A"},
  {"id":"MBH01008","name":"Medica Nursing Home","district":"Kolkata","location":"Ballygunge","password":"NH66AE69"},
  {"id":"MBH01009","name":"Fortis Healthcare","district":"Kolkata","location":"Dumdum","password":"NH77DEA9"},
  {"id":"MBH01010","name":"Columbia Care Centre","district":"Kolkata","location":"Park Street","password":"NHDCD5B6"},
  {"id":"MBH02001","name":"Seva Medicare","district":"Howrah","location":"Shibpur","password":"NH3299EE"},
  {"id":"MBH02002","name":"Lakshmi Nursing Home","district":"Howrah","location":"Bally","password":"NHF2284D"},
  {"id":"MBH02003","name":"Saraswati Healthcare","district":"Howrah","location":"Liluah","password":"NH951C83"},
  {"id":"MBH02004","name":"Durga Care Centre","district":"Howrah","location":"Uluberia","password":"NHA778B8"},
  {"id":"MBH02005","name":"Kali Hospital","district":"Howrah","location":"Santragachi","password":"NH9DBBCC"},
  {"id":"MBH02006","name":"Bishwanath Clinic","district":"Howrah","location":"Domjur","password":"NH085F8D"},
  {"id":"MBH02007","name":"Ramakrishna Super Speciality","district":"Howrah","location":"Andul","password":"NHA1DC2F"},
  {"id":"MBH02008","name":"Vivekananda Health Institute","district":"Howrah","location":"Bagnan","password":"NH771589"},
  {"id":"MBH02009","name":"Subarna Medical Centre","district":"Howrah","location":"Rampur","password":"NH00150B"},
  {"id":"MBH02010","name":"Uttarayan Multispeciality Hospital","district":"Howrah","location":"Kona","password":"NH6A76E7"},
  {"id":"MBH03001","name":"Modern Super Speciality","district":"Hooghly","location":"Chinsurah","password":"NHBDAB06"},
  {"id":"MBH03002","name":"Advanced Health Institute","district":"Hooghly","location":"Serampore","password":"NHDA907A"},
  {"id":"MBH03003","name":"Primary Medical Centre","district":"Hooghly","location":"Tarakeswar","password":"NH831355"},
  {"id":"MBH03004","name":"Community Multispeciality Hospital","district":"Hooghly","location":"Arambagh","password":"NH0CE72F"},
  {"id":"MBH03005","name":"General Medicare","district":"Hooghly","location":"Konnagar","password":"NH480775"},
  {"id":"MBH03006","name":"Welfare Nursing Home","district":"Hooghly","location":"Bandel","password":"NH4C1EA1"},
  {"id":"MBH03007","name":"Sanjeevani Healthcare","district":"Hooghly","location":"Dankuni","password":"NH5FE74A"},
  {"id":"MBH03008","name":"Arogya Care Centre","district":"Hooghly","location":"Mogra","password":"NHEB66C2"},
  {"id":"MBH03009","name":"Swasthya Hospital","district":"Hooghly","location":"Titagarh","password":"NH501A78"},
  {"id":"MBH03010","name":"Nirmala Clinic","district":"Hooghly","location":"Hugli-Chuchura","password":"NH2FE2A2"},
  {"id":"MBH04001","name":"Sarvodaya Healthcare","district":"North 24 Parganas","location":"Barasat","password":"NHAE3692"},
  {"id":"MBH04002","name":"Lifeline Care Centre","district":"North 24 Parganas","location":"Barrackpore","password":"NHDD979B"},
  {"id":"MBH04003","name":"Sunrise Hospital","district":"North 24 Parganas","location":"Madhyamgram","password":"NH55F76E"},
  {"id":"MBH04004","name":"Metro Clinic","district":"North 24 Parganas","location":"Khardaha","password":"NH3F80E6"},
  {"id":"MBH04005","name":"City Super Speciality","district":"North 24 Parganas","location":"Belgharia","password":"NHA25953"},
  {"id":"MBH04006","name":"District Health Institute","district":"North 24 Parganas","location":"Naihati","password":"NHA08E7F"},
  {"id":"MBH04007","name":"People's Medical Centre","district":"North 24 Parganas","location":"Bongaon","password":"NHEC79A3"},
  {"id":"MBH04008","name":"National Multispeciality Hospital","district":"North 24 Parganas","location":"Amdanga","password":"NH0A663C"},
  {"id":"MBH04009","name":"Central Medicare","district":"North 24 Parganas","location":"Basirhat","password":"NHC20D42"},
  {"id":"MBH04010","name":"Green Park Nursing Home","district":"North 24 Parganas","location":"Habra","password":"NH99F2DB"},
  {"id":"MBH05001","name":"Nibedita Medical Centre","district":"South 24 Parganas","location":"Diamond Harbour","password":"NHC8114F"},
  {"id":"MBH05002","name":"Pratibha Multispeciality Hospital","district":"South 24 Parganas","location":"Baruipur","password":"NH103132"},
  {"id":"MBH05003","name":"Apollo Medicare","district":"South 24 Parganas","location":"Canning","password":"NH435C61"},
  {"id":"MBH05004","name":"Peerless Nursing Home","district":"South 24 Parganas","location":"Budge Budge","password":"NH6DC3F1"},
  {"id":"MBH05005","name":"AMRI Healthcare","district":"South 24 Parganas","location":"Maheshtala","password":"NH219CFC"},
  {"id":"MBH05006","name":"Ruby Care Centre","district":"South 24 Parganas","location":"Sonarpur","password":"NH5B8B9A"},
  {"id":"MBH05007","name":"Belle Vue Hospital","district":"South 24 Parganas","location":"Namkhana","password":"NH27DC5B"},
  {"id":"MBH05008","name":"Woodlands Clinic","district":"South 24 Parganas","location":"Kakdwip","password":"NH9332AB"},
  {"id":"MBH05009","name":"Desun Super Speciality","district":"South 24 Parganas","location":"Raidighi","password":"NH960A49"},
  {"id":"MBH05010","name":"Medica Health Institute","district":"South 24 Parganas","location":"Joynagar","password":"NH75A7A5"},
  {"id":"MBH06001","name":"Jeevan Hospital","district":"Nadia","location":"Krishnanagar","password":"NH930E80"},
  {"id":"MBH06002","name":"Ananda Clinic","district":"Nadia","location":"Kalyani","password":"NHAE42FF"},
  {"id":"MBH06003","name":"Seva Super Speciality","district":"Nadia","location":"Ranaghat","password":"NHEDC4A4"},
  {"id":"MBH06004","name":"Lakshmi Health Institute","district":"Nadia","location":"Shantipur","password":"NH982354"},
  {"id":"MBH06005","name":"Saraswati Medical Centre","district":"Nadia","location":"Karimpur","password":"NH1C8949"},
  {"id":"MBH06006","name":"Durga Multispeciality Hospital","district":"Nadia","location":"Tehatta","password":"NHC1313B"},
  {"id":"MBH06007","name":"Kali Medicare","district":"Nadia","location":"Nabadwip","password":"NH0C2E73"},
  {"id":"MBH06008","name":"Bishwanath Nursing Home","district":"Nadia","location":"Palashbari","password":"NHBC7C48"},
  {"id":"MBH06009","name":"Ramakrishna Healthcare","district":"Nadia","location":"Hanskhali","password":"NH82C0EE"},
  {"id":"MBH06010","name":"Vivekananda Care Centre","district":"Nadia","location":"Birnagar","password":"NH70FE27"},
  {"id":"MBH07001","name":"Riverside Medicare","district":"Murshidabad","location":"Baharampur","password":"NH8AE659"},
  {"id":"MBH07002","name":"Heritage Nursing Home","district":"Murshidabad","location":"Jiaganj","password":"NH9E6B91"},
  {"id":"MBH07003","name":"Modern Healthcare","district":"Murshidabad","location":"Azimganj","password":"NH4427D3"},
  {"id":"MBH07004","name":"Advanced Care Centre","district":"Murshidabad","location":"Kandi","password":"NH893DC5"},
  {"id":"MBH07005","name":"Primary Hospital","district":"Murshidabad","location":"Lalbagh","password":"NH457F97"},
  {"id":"MBH07006","name":"Community Clinic","district":"Murshidabad","location":"Beldanga","password":"NH76AC0E"},
  {"id":"MBH07007","name":"General Super Speciality","district":"Murshidabad","location":"Farakka","password":"NH81C573"},
  {"id":"MBH07008","name":"Welfare Health Institute","district":"Murshidabad","location":"Jangipur","password":"NH580624"},
  {"id":"MBH07009","name":"Sanjeevani Medical Centre","district":"Murshidabad","location":"Domkal","password":"NHC47B34"},
  {"id":"MBH07010","name":"Arogya Multispeciality Hospital","district":"Murshidabad","location":"Lalgola","password":"NH65F3E9"},
  {"id":"MBH08001","name":"Columbia Super Speciality","district":"Birbhum","location":"Bolpur","password":"NHCA978B"},
  {"id":"MBH08002","name":"Care Health Institute","district":"Birbhum","location":"Suri","password":"NHF6F985"},
  {"id":"MBH08003","name":"Sarvodaya Medical Centre","district":"Birbhum","location":"Rampurhat","password":"NHA27E11"},
  {"id":"MBH08004","name":"Lifeline Multispeciality Hospital","district":"Birbhum","location":"Dubrajpur","password":"NHD3330F"},
  {"id":"MBH08005","name":"Sunrise Medicare","district":"Birbhum","location":"Nalhati","password":"NH1BD8AF"},
  {"id":"MBH08006","name":"Metro Nursing Home","district":"Birbhum","location":"Sainthia","password":"NH23718B"},
  {"id":"MBH08007","name":"City Healthcare","district":"Birbhum","location":"Ilambazar","password":"NH4941A7"},
  {"id":"MBH08008","name":"District Care Centre","district":"Birbhum","location":"Mohammadbazar","password":"NH3A9A48"},
  {"id":"MBH08009","name":"People's Hospital","district":"Birbhum","location":"Hansan","password":"NHE9E255"},
  {"id":"MBH08010","name":"National Clinic","district":"Birbhum","location":"Mayureswar","password":"NHD198DA"},
  {"id":"MBH09001","name":"Uttarayan Healthcare","district":"Purba Bardhaman","location":"Asansol","password":"NH8F2565"},
  {"id":"MBH09002","name":"Prantik Care Centre","district":"Purba Bardhaman","location":"Durgapur","password":"NH1A1C50"},
  {"id":"MBH09003","name":"Nibedita Hospital","district":"Purba Bardhaman","location":"Kalna","password":"NH7BD7FF"},
  {"id":"MBH09004","name":"Pratibha Clinic","district":"Purba Bardhaman","location":"Katwa","password":"NH2D5E4C"},
  {"id":"MBH09005","name":"Apollo Super Speciality","district":"Purba Bardhaman","location":"Memari","password":"NH025DE1"},
  {"id":"MBH09006","name":"Peerless Health Institute","district":"Purba Bardhaman","location":"Sadar","password":"NHC688E0"},
  {"id":"MBH09007","name":"AMRI Medical Centre","district":"Purba Bardhaman","location":"Galsi","password":"NH23D756"},
  {"id":"MBH09008","name":"Ruby Multispeciality Hospital","district":"Purba Bardhaman","location":"Burdwan","password":"NH8B7764"},
  {"id":"MBH09009","name":"Belle Vue Medicare","district":"Purba Bardhaman","location":"Bhatar","password":"NHBF3360"},
  {"id":"MBH09010","name":"Woodlands Nursing Home","district":"Purba Bardhaman","location":"Pandabeswar","password":"NH89AC1F"},
  {"id":"MBH10001","name":"Nirmala Medical Centre","district":"Purulia","location":"Purulia Town","password":"NH1B8847"},
  {"id":"MBH10002","name":"Shanti Multispeciality Hospital","district":"Purulia","location":"Raghunathpur","password":"NH3A9D19"},
  {"id":"MBH10003","name":"Jeevan Medicare","district":"Purulia","location":"Jhalda","password":"NH650FB1"},
  {"id":"MBH10004","name":"Ananda Nursing Home","district":"Purulia","location":"Balarampur","password":"NHEA3110"},
  {"id":"MBH10005","name":"Seva Healthcare","district":"Purulia","location":"Hura","password":"NH4E7C4C"},
  {"id":"MBH10006","name":"Lakshmi Care Centre","district":"Purulia","location":"Manbazar","password":"NHB01C6D"},
  {"id":"MBH10007","name":"Saraswati Hospital","district":"Purulia","location":"Kashipur","password":"NH42D4B5"},
  {"id":"MBH10008","name":"Durga Clinic","district":"Purulia","location":"Arsha","password":"NH42FF7C"},
  {"id":"MBH10009","name":"Kali Super Speciality","district":"Purulia","location":"Bagmundi","password":"NHB55301"},
  {"id":"MBH10010","name":"Bishwanath Health Institute","district":"Purulia","location":"Bamni","password":"NH3C0942"},
  {"id":"MBH11001","name":"Green Park Hospital","district":"Jalpaiguri","location":"Mal Bazar","password":"NH6B7EF2"},
  {"id":"MBH11002","name":"Garden City Clinic","district":"Jalpaiguri","location":"Kadamtala","password":"NH1EA741"},
  {"id":"MBH11003","name":"Riverside Super Speciality","district":"Jalpaiguri","location":"Maynaguri","password":"NH8D0253"},
  {"id":"MBH11004","name":"Heritage Health Institute","district":"Jalpaiguri","location":"Nagrakata","password":"NH271E92"},
  {"id":"MBH11005","name":"Modern Medical Centre","district":"Jalpaiguri","location":"Dhupguri","password":"NHD03A1E"},
  {"id":"MBH11006","name":"Advanced Multispeciality Hospital","district":"Jalpaiguri","location":"Rajganj","password":"NH1DEFDD"},
  {"id":"MBH11007","name":"Primary Medicare","district":"Jalpaiguri","location":"Belakoba","password":"NH43834B"},
  {"id":"MBH11008","name":"Community Nursing Home","district":"Jalpaiguri","location":"Banarhat","password":"NH333862"},
  {"id":"MBH11009","name":"General Healthcare","district":"Jalpaiguri","location":"Chalsa","password":"NHB49F3F"},
  {"id":"MBH11010","name":"Welfare Care Centre","district":"Jalpaiguri","location":"Ambari","password":"NHDB94A4"},
  {"id":"MBH12001","name":"Medica Medicare","district":"Darjeeling","location":"Ghoom","password":"NH76FAB0"},
  {"id":"MBH12002","name":"Fortis Nursing Home","district":"Darjeeling","location":"Kurseong","password":"NH75D542"},
  {"id":"MBH12003","name":"Columbia Healthcare","district":"Darjeeling","location":"Mirik","password":"NH80C4F9"},
  {"id":"MBH12004","name":"Care Care Centre","district":"Darjeeling","location":"Sonada","password":"NH5CFAAE"},
  {"id":"MBH12005","name":"Sarvodaya Hospital","district":"Darjeeling","location":"Lebong","password":"NH4D4E3E"},
  {"id":"MBH12006","name":"Lifeline Clinic","district":"Darjeeling","location":"Ghum","password":"NH257E63"},
  {"id":"MBH12007","name":"Sunrise Super Speciality","district":"Darjeeling","location":"Rimbick","password":"NH2E2F5A"},
  {"id":"MBH12008","name":"Metro Health Institute","district":"Darjeeling","location":"Bijanbari","password":"NH5E6E9F"},
  {"id":"MBH12009","name":"City Medical Centre","district":"Darjeeling","location":"Tindharia","password":"NH329457"},
  {"id":"MBH12010","name":"District Multispeciality Hospital","district":"Darjeeling","location":"Tung","password":"NH8F7485"},
  {"id":"MBH13001","name":"Vivekananda Super Speciality","district":"Alipurduar","location":"Alipurduar Town","password":"NH199EA9"},
  {"id":"MBH13002","name":"Subarna Health Institute","district":"Alipurduar","location":"Falakata","password":"NH8D05B9"},
  {"id":"MBH13003","name":"Uttarayan Medical Centre","district":"Alipurduar","location":"Birpara","password":"NH1A8EA5"},
  {"id":"MBH13004","name":"Prantik Multispeciality Hospital","district":"Alipurduar","location":"Hasimara","password":"NH52727F"},
  {"id":"MBH13005","name":"Nibedita Medicare","district":"Alipurduar","location":"Madarihat","password":"NH61EAEA"},
  {"id":"MBH13006","name":"Pratibha Nursing Home","district":"Alipurduar","location":"Kalchini","password":"NH95AD94"},
  {"id":"MBH13007","name":"Apollo Healthcare","district":"Alipurduar","location":"Samuktala","password":"NH4A4FF1"},
  {"id":"MBH13008","name":"Peerless Care Centre","district":"Alipurduar","location":"Jaygaon","password":"NH0DAAA8"},
  {"id":"MBH13009","name":"AMRI Hospital","district":"Alipurduar","location":"Samsing","password":"NH0EEAE1"},
  {"id":"MBH13010","name":"Ruby Clinic","district":"Alipurduar","location":"Buxa","password":"NHEF682D"},
  {"id":"MBH14001","name":"Arogya Healthcare","district":"Bankura","location":"Bishnupur","password":"NHBC69F0"},
  {"id":"MBH14002","name":"Swasthya Care Centre","district":"Bankura","location":"Bankura Town","password":"NHEB54C9"},
  {"id":"MBH14003","name":"Nirmala Hospital","district":"Bankura","location":"Khatra","password":"NH8DD117"},
  {"id":"MBH14004","name":"Shanti Clinic","district":"Bankura","location":"Ranibandh","password":"NH52C2C0"},
  {"id":"MBH14005","name":"Jeevan Super Speciality","district":"Bankura","location":"Barjora","password":"NHBC1066"},
  {"id":"MBH14006","name":"Ananda Health Institute","district":"Bankura","location":"Indas","password":"NHB3FE60"},
  {"id":"MBH14007","name":"Seva Medical Centre","district":"Bankura","location":"Chhatna","password":"NH11116B"},
  {"id":"MBH14008","name":"Lakshmi Multispeciality Hospital","district":"Bankura","location":"Saltora","password":"NHACD7BD"},
  {"id":"MBH14009","name":"Saraswati Medicare","district":"Bankura","location":"Sonamukhi","password":"NHCD435C"},
  {"id":"MBH14010","name":"Durga Nursing Home","district":"Bankura","location":"Onda","password":"NHF63B87"},
  {"id":"MBH15001","name":"National Medical Centre","district":"Cooch Behar","location":"Cooch Behar Town","password":"NHD6A633"},
  {"id":"MBH15002","name":"Central Multispeciality Hospital","district":"Cooch Behar","location":"Tufanganj","password":"NH88A3D6"},
  {"id":"MBH15003","name":"Green Park Medicare","district":"Cooch Behar","location":"Dinhata","password":"NH35980A"},
  {"id":"MBH15004","name":"Garden City Nursing Home","district":"Cooch Behar","location":"Mekhliganj","password":"NH4BE34D"},
  {"id":"MBH15005","name":"Riverside Healthcare","district":"Cooch Behar","location":"Sitalkuchi","password":"NH25E2BF"},
  {"id":"MBH15006","name":"Heritage Care Centre","district":"Cooch Behar","location":"Mathabhanga","password":"NH769C87"},
  {"id":"MBH15007","name":"Modern Hospital","district":"Cooch Behar","location":"Ananda Nagar","password":"NH1D5B38"},
  {"id":"MBH15008","name":"Advanced Clinic","district":"Cooch Behar","location":"Gitaldaha","password":"NH6BB110"},
  {"id":"MBH15009","name":"Primary Super Speciality","district":"Cooch Behar","location":"Balarampur","password":"NH2B1C04"},
  {"id":"MBH15010","name":"Community Health Institute","district":"Cooch Behar","location":"Gossaigaon","password":"NH2B5B6D"},
  {"id":"MBH16001","name":"Woodlands Hospital","district":"Dakshin Dinajpur","location":"Balurghat","password":"NH31D241"},
  {"id":"MBH16002","name":"Desun Clinic","district":"Dakshin Dinajpur","location":"Gangarampur","password":"NH3FB9C1"},
  {"id":"MBH16003","name":"Medica Super Speciality","district":"Dakshin Dinajpur","location":"Kumarganj","password":"NH952B2C"},
  {"id":"MBH16004","name":"Fortis Health Institute","district":"Dakshin Dinajpur","location":"Harirampur","password":"NH5503BB"},
  {"id":"MBH16005","name":"Columbia Medical Centre","district":"Dakshin Dinajpur","location":"Hili","password":"NH18ED70"},
  {"id":"MBH16006","name":"Care Multispeciality Hospital","district":"Dakshin Dinajpur","location":"Tapan","password":"NHD162FF"},
  {"id":"MBH16007","name":"Sarvodaya Medicare","district":"Dakshin Dinajpur","location":"Banshihari","password":"NHC00FBC"},
  {"id":"MBH16008","name":"Lifeline Nursing Home","district":"Dakshin Dinajpur","location":"Bhamra","password":"NH394C3F"},
  {"id":"MBH16009","name":"Sunrise Healthcare","district":"Dakshin Dinajpur","location":"Kushmandi","password":"NH95820A"},
  {"id":"MBH16010","name":"Metro Care Centre","district":"Dakshin Dinajpur","location":"Mange","password":"NHBA70C3"},
  {"id":"MBH17001","name":"Bishwanath Medicare","district":"Malda","location":"English Bazar","password":"NH3B7E12"},
  {"id":"MBH17002","name":"Ramakrishna Nursing Home","district":"Malda","location":"Old Malda","password":"NHFA42C3"},
  {"id":"MBH17003","name":"Vivekananda Healthcare","district":"Malda","location":"Ratua","password":"NH7549A6"},
  {"id":"MBH17004","name":"Subarna Care Centre","district":"Malda","location":"Gazole","password":"NHD8566F"},
  {"id":"MBH17005","name":"Uttarayan Hospital","district":"Malda","location":"Kaliachak","password":"NH5C0182"},
  {"id":"MBH17006","name":"Prantik Clinic","district":"Malda","location":"Manikchak","password":"NH54AFF2"},
  {"id":"MBH17007","name":"Nibedita Super Speciality","district":"Malda","location":"Harishchandrapur","password":"NHB423CC"},
  {"id":"MBH17008","name":"Pratibha Health Institute","district":"Malda","location":"Chanchal","password":"NHBB47B6"},
  {"id":"MBH17009","name":"Apollo Medical Centre","district":"Malda","location":"Habibpur","password":"NHE1FF8E"},
  {"id":"MBH17010","name":"Peerless Multispeciality Hospital","district":"Malda","location":"Bamangola","password":"NH1439A8"},
  {"id":"MBH18001","name":"Welfare Super Speciality","district":"Paschim Medinipur","location":"Kharagpur","password":"NH959A9B"},
  {"id":"MBH18002","name":"Sanjeevani Health Institute","district":"Paschim Medinipur","location":"Midnapore","password":"NH728E60"},
  {"id":"MBH18003","name":"Arogya Medical Centre","district":"Paschim Medinipur","location":"Ghatal","password":"NHD5EA47"},
  {"id":"MBH18004","name":"Swasthya Multispeciality Hospital","district":"Paschim Medinipur","location":"Pingla","password":"NH2A9527"},
  {"id":"MBH18005","name":"Nirmala Medicare","district":"Paschim Medinipur","location":"Keshiary","password":"NH6163DA"},
  {"id":"MBH18006","name":"Shanti Nursing Home","district":"Paschim Medinipur","location":"Chandrakona","password":"NH7CC94F"},
  {"id":"MBH18007","name":"Jeevan Healthcare","district":"Paschim Medinipur","location":"Garbeta","password":"NH2F952C"},
  {"id":"MBH18008","name":"Ananda Care Centre","district":"Paschim Medinipur","location":"Salboni","password":"NHB4033B"},
  {"id":"MBH18009","name":"Seva Hospital","district":"Paschim Medinipur","location":"Egra","password":"NHD57ED2"},
  {"id":"MBH18010","name":"Lakshmi Clinic","district":"Paschim Medinipur","location":"Narayangarh","password":"NHFFBAB6"},
  {"id":"MBH19001","name":"District Healthcare","district":"Purba Medinipur","location":"Tamluk","password":"NHD54E55"},
  {"id":"MBH19002","name":"People's Care Centre","district":"Purba Medinipur","location":"Contai","password":"NH62D20B"},
  {"id":"MBH19003","name":"National Hospital","district":"Purba Medinipur","location":"Haldia","password":"NH035BC1"},
  {"id":"MBH19004","name":"Central Clinic","district":"Purba Medinipur","location":"Kanthi","password":"NH321A81"},
  {"id":"MBH19005","name":"Green Park Super Speciality","district":"Purba Medinipur","location":"Nayachar","password":"NH3012F5"},
  {"id":"MBH19006","name":"Garden City Health Institute","district":"Purba Medinipur","location":"Ramachandrapur","password":"NH8CCF76"},
  {"id":"MBH19007","name":"Riverside Medical Centre","district":"Purba Medinipur","location":"Egra","password":"NH22E70C"},
  {"id":"MBH19008","name":"Heritage Multispeciality Hospital","district":"Purba Medinipur","location":"Mahisadal","password":"NH630F42"},
  {"id":"MBH19009","name":"Modern Medicare","district":"Purba Medinipur","location":"Ramnagar","password":"NHCD971F"},
  {"id":"MBH19010","name":"Advanced Nursing Home","district":"Purba Medinipur","location":"Nandigram","password":"NH9E4789"},
  {"id":"MBH20001","name":"Ruby Medical Centre","district":"Paschim Bardhaman","location":"Asansol","password":"NH60E029"},
  {"id":"MBH20002","name":"Belle Vue Multispeciality Hospital","district":"Paschim Bardhaman","location":"Raniganj","password":"NH193F3A"},
  {"id":"MBH20003","name":"Woodlands Medicare","district":"Paschim Bardhaman","location":"Kulti","password":"NHBE14F4"},
  {"id":"MBH20004","name":"Desun Nursing Home","district":"Paschim Bardhaman","location":"Jamuria","password":"NH8F13A2"},
  {"id":"MBH20005","name":"Medica Healthcare","district":"Paschim Bardhaman","location":"Pandaveswar","password":"NH8A4427"},
  {"id":"MBH20006","name":"Fortis Care Centre","district":"Paschim Bardhaman","location":"Salanpur","password":"NH7E7ADC"},
  {"id":"MBH20007","name":"Columbia Hospital","district":"Paschim Bardhaman","location":"Barakar","password":"NH19FD0B"},
  {"id":"MBH20008","name":"Care Clinic","district":"Paschim Bardhaman","location":"Chittaranjan","password":"NH1D5B45"},
  {"id":"MBH20009","name":"Sarvodaya Super Speciality","district":"Paschim Bardhaman","location":"Dhawalgiri","password":"NH1F1DB1"},
  {"id":"MBH20010","name":"Lifeline Health Institute","district":"Paschim Bardhaman","location":"Bermo","password":"NHD89104"},
  {"id":"MBH21001","name":"Durga Hospital","district":"Jhargram","location":"Jhargram Town","password":"NH27A022"},
  {"id":"MBH21002","name":"Kali Clinic","district":"Jhargram","location":"Gopiballavpur","password":"NH773194"},
  {"id":"MBH21003","name":"Bishwanath Super Speciality","district":"Jhargram","location":"Silda","password":"NHE60285"},
  {"id":"MBH21004","name":"Ramakrishna Health Institute","district":"Jhargram","location":"Binpur","password":"NH38F4C8"},
  {"id":"MBH21005","name":"Vivekananda Medical Centre","district":"Jhargram","location":"Belpahari","password":"NH4A6528"},
  {"id":"MBH21006","name":"Subarna Multispeciality Hospital","district":"Jhargram","location":"Lalgarh","password":"NH75015C"},
  {"id":"MBH21007","name":"Uttarayan Medicare","district":"Jhargram","location":"Sabang","password":"NH624C47"},
  {"id":"MBH21008","name":"Prantik Nursing Home","district":"Jhargram","location":"Nayagram","password":"NH224099"},
  {"id":"MBH21009","name":"Nibedita Healthcare","district":"Jhargram","location":"Dantan","password":"NH872FAC"},
  {"id":"MBH21010","name":"Pratibha Care Centre","district":"Jhargram","location":"Sankrail","password":"NH41DDF2"},
  {"id":"MBH22001","name":"Community Medicare","district":"Uttar Dinajpur","location":"Raiganj","password":"NH39D327"},
  {"id":"MBH22002","name":"General Nursing Home","district":"Uttar Dinajpur","location":"Islampur","password":"NHBD24BC"},
  {"id":"MBH22003","name":"Welfare Healthcare","district":"Uttar Dinajpur","location":"Dalkhola","password":"NHB46B93"},
  {"id":"MBH22004","name":"Sanjeevani Care Centre","district":"Uttar Dinajpur","location":"Chopra","password":"NH552681"},
  {"id":"MBH22005","name":"Arogya Hospital","district":"Uttar Dinajpur","location":"Kaliyaganj","password":"NH0C4617"},
  {"id":"MBH22006","name":"Swasthya Clinic","district":"Uttar Dinajpur","location":"Goalpokhar","password":"NH0CC181"},
  {"id":"MBH22007","name":"Nirmala Super Speciality","district":"Uttar Dinajpur","location":"Itahar","password":"NH7F1FCE"},
  {"id":"MBH22008","name":"Shanti Health Institute","district":"Uttar Dinajpur","location":"Raninagar","password":"NH6FAB06"},
  {"id":"MBH22009","name":"Jeevan Medical Centre","district":"Uttar Dinajpur","location":"Karandighi","password":"NHF91B76"},
  {"id":"MBH22010","name":"Ananda Multispeciality Hospital","district":"Uttar Dinajpur","location":"Haripur","password":"NHD9B4A9"},
  {"id":"MBH23001","name":"Metro Super Speciality","district":"Kalimpong","location":"Kalimpong Town","password":"NH285880"},
  {"id":"MBH23002","name":"City Health Institute","district":"Kalimpong","location":"Algarah","password":"NH971BC0"},
  {"id":"MBH23003","name":"District Medical Centre","district":"Kalimpong","location":"Lava","password":"NH175D09"},
  {"id":"MBH23004","name":"People's Multispeciality Hospital","district":"Kalimpong","location":"Labha","password":"NH6C3700"},
  {"id":"MBH23005","name":"National Medicare","district":"Kalimpong","location":"Relli","password":"NHA1EBB0"},
  {"id":"MBH23006","name":"Central Nursing Home","district":"Kalimpong","location":"Mefti","password":"NHE3D6A5"},
  {"id":"MBH23007","name":"Green Park Healthcare","district":"Kalimpong","location":"Gorubathan","password":"NHD3C30A"},
  {"id":"MBH23008","name":"Garden City Care Centre","district":"Kalimpong","location":"Jhalong","password":"NHF28CE0"},
  {"id":"MBH23009","name":"Riverside Hospital","district":"Kalimpong","location":"Sillery Gaon","password":"NH260D9C"},
  {"id":"MBH23010","name":"Heritage Clinic","district":"Kalimpong","location":"Samardong","password":"NH64995E"}
];